### ISSUE TITLE
Clarify difference from financius-public in README?

### ISSUE THREAD

**Issue by patcon** [mvarnagiris/financius#1]
Not sure I understand the distinction, but I'm worried it means you're going closed source or two tiered.

I'd like to be clear on the siutation before enthusiastically promoting and supporting the project around my corners of the internet. Thanks for everything regardless!

**Comment by mvarnagiris** [comment]
Current Financius latest version is closed source. I will move it to open source as soon as I have time. This will be a new app. So both apps will be opensource. I'm making a new app because this will be a very different concept from the original Financius. I'll update the readme. Not sure how I'm gonna support the old one yet.

**Comment by patcon** [comment]
Thanks @mvarnagiris! I guess the main thing is that you can be financially supported (which you deserve), and I hope that can somehow involve open source.

Would it make sense if I opened an issue called "Allow use to financially support the project", so that people could +1 that and you could ping back when some paid app version is available to buy?

**Comment by mvarnagiris** [comment]
I plan to make this version paid somehow. Not sure how yet. I'll have to think about it. For this project its a bit too early for contributions. Unless something small. And it would be best to have a chat with me before doing. I appreciate your support ;)

**Comment by patcon** [comment]
Totally. That makes sense. Thanks for everything man :)

**Comment by megapctr** [comment]
:+1: You could add a FAQ section in the readme and point to this issue

Could you elaborate on why you closed financius source?

**Comment by mvarnagiris** [comment]
I will update Financius source to the latest at some point when I have time and let community support it as I don't have much time to do that as this has become my main project.

**Comment by avseredyuk** [comment]
Is there any way to speed up updating of the sources to the latest 0.19.7 ?
