### ISSUE TITLE
Financius as a group expense manager

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#10]
It would be very useful to be able to use Financius to track group expenses, i.e. an event enjoyed by several people who share the costs, like a picnic or a party.

![financius group 1](https://f.cloud.github.com/assets/694794/1509807/c5f1be82-4a64-11e3-8a9c-76df86997767.png)

Here's a Groups screen showing two different groups. In one of them you're owed money by the other participants, in the other you owe it.

![financius group 2](https://f.cloud.github.com/assets/694794/1509813/eaf83850-4a64-11e3-981c-616b790601e0.png)

Here's the details screen of a group. It shows your unsettled debts with other participants and lets you create transactions to settle them. It also lets you see debts between the other participants, but those are hidden by default.

It also shows you a list of the group's expenses, which are important because they're what cause debts between participants.

![financius group 3](https://f.cloud.github.com/assets/694794/1509820/68f6e652-4a65-11e3-9cbf-140e4ae7976c.png)

When you add an expense to the group, you can specify which participant (or participants) paid for it (using the From field), and who enjoyed it (using the To field). If a participant pays for an expense and the others enjoy it, they will owe him money and that will show in the group's Balance card.

![financius group editor](https://f.cloud.github.com/assets/694794/1509794/2de6c434-4a64-11e3-94ae-eec0b7413b27.png)

When you want to create a group you have to specify its name, its participants and the category it belongs to. You can also add a note or description for it.

**Comment by mvarnagiris** [comment]
It's an interesting concept, but at the moment it doesn't fall under the purpose of this app. If this feature is going to be implemented, it will be only we get everything else right

**Comment by frandavid100** [comment]
Absolutely. This is a very long-term suggestion. It would be nice to eventually have it, though.

**Comment by mvarnagiris** [comment]
A lot of things might change in that long time :) That's why I think it's not worth having this here until it's decided to implement this feature.

**Comment by frandavid100** [comment]
Agreed. Let's hope the issue is reopened in the future.
