### ISSUE TITLE
Backup progress

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#100]
Background activity confusing me. Sometimes I wait 5-8 seconds before "success" tooltip will be shown. Can you add any progress animation to "your data" screen? (Circle or progressbar like in gmail/Engadget/google drive)

**Comment by mvarnagiris** [comment]
That's a good point

**Comment by ghost** [comment]
This would be a neat feature, yes. As it is now, I "must" wait until the message "backup completed" appears to be sure that Financius really backed up my data.

**Comment by mvarnagiris** [comment]
GDrive backup is going away in next release
