### ISSUE TITLE
Bug in "Period" section accessible by swiping from right...

### ISSUE THREAD

**Issue by maheshkhatual** [mvarnagiris/financius#101]
I think this provision is to find out transactions & reports for a particular period. Very useful. Great idea! But we can't execute the same due to some bug.
![screenshot_2014-02-19-12-10-56](https://f.cloud.github.com/assets/6755134/2254721/2a6ec666-9de4-11e3-8817-ba2ef35588df.png)

**Comment by mvarnagiris** [comment]
Duplicate #60 #20
