### ISSUE TITLE
Autosuggest Notes

### ISSUE THREAD

**Issue by pongthaic** [mvarnagiris/financius#107]
Would be nice to have an autocomplete for the note field from history when entering transaction register.

**Comment by mvarnagiris** [comment]
Why would you want to repeat same notes? There will be _tags_ in new updated, maybe they are more suitable for repeated notes

**Comment by philipgiuliani** [comment]
In the note i currently write in which restaurant i spend the money for example. If i go to that restaurant every day i need to write everyday the full name of it. So autocompletion would be cool!

If i wrote "McDonald's" one time, it should remember it and the next time when i just write "M" i should get the suggestion of McDonald's

**Comment by mvarnagiris** [comment]
Done
