### ISSUE TITLE
Financius as a lending manager

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#11]
It would be useful to be able to use Financius to track your lendings with other people:

![financius lendings 1](https://f.cloud.github.com/assets/694794/1509837/a45beebc-4a66-11e3-97ef-fd177fd999e6.png)

Here's the lendings list, showing you that two contacts have unsettled debts with you. One owes you money, the other is owed.

![financius lendings 2](https://f.cloud.github.com/assets/694794/1509856/d956ec10-4a67-11e3-982c-65c820b27f73.png)

This is the details screen for a particular contact, complete with your history with that contact. That history includes both direct lendings and debts caused by group expenses.

![financius lendings 3](https://f.cloud.github.com/assets/694794/1509860/07d7d5f4-4a68-11e3-87df-8653038d72a3.png)

If you press Lend, Borrow or Settle debt, a new transaction is created between you and the contact: If you press Lend the contact's name autofills the To field, and if you press Borrow it autofills From. If you press Settle debt, however, the name of the person who is owed fills the To field, and the money owed fills the Amount field.

In addition to money lendings, this system can be used for item lendings. If you fill the Concept field but leave Amount empty, the app considers that you have lent an item (e.g. a book or a DVD).

**Comment by AFirooz** [comment]
+1 to this

**Comment by mvarnagiris** [comment]
#28 Would have the ability to track loans
