### ISSUE TITLE
Move settings menu to the left pane.

### ISSUE THREAD

**Issue by xenogew** [mvarnagiris/financius#110]
I suggest you that it will be better if you move 3 dots settings menu on the right-top to be on the left hiding-pane.

I think it will be clean and lovely.
Wish you will consider this.

The image that represent my idea.
![screenshot_2014-03-28-18-40-27](https://cloud.githubusercontent.com/assets/756484/2549121/3ef9b1ec-b66f-11e3-8e53-80021a22e231.png)

**Comment by assoc** [comment]
+1, but edit/delete button must be saved at right side of top panel

**Comment by mvarnagiris** [comment]
It's a fair suggestion as Google apps are moving to this direction

**Comment by firnasz** [comment]
+1

**Comment by blakadder** [comment]
+1, would streamline it more with other android apps

**Comment by mvarnagiris** [comment]
Done
