### ISSUE TITLE
Filter / Custom View of Transactions

### ISSUE THREAD

**Issue by firnasz** [mvarnagiris/financius#111]
When it comes to large amount of transactions like at least 3 months of data, it will be difficult to dig through old data, because we have to scroll down a lot. 

It is very useful if we have an option to customize the transactions screen such as filter to see what we want for example, 
- show current month transactions
- show last month transactions
- show transactions of a specific category or subcategory
- show transactions within a specific date range
- show transaction of a specific account

Thank you.

**Comment by mvarnagiris** [comment]
Duplicate #20
