### ISSUE TITLE
Auto Backup to GDrive on every transaction/modification made!

### ISSUE THREAD

**Issue by maheshkhatual** [mvarnagiris/financius#112]
Manual Backup is not always reliable. We may lose data on lost/crashing etc. of phone. So it may be considered to implement auto backup of data to GDrive on each transaction/modification made. Other apps have implemented this successfully. It is much more reliable than manual backup.

**Comment by xenogew** [comment]
+1,

this is great.

**Comment by assoc** [comment]
Best solution is api's used in Timetable app by G. Ittner (sync using Google account)

**Comment by mvarnagiris** [comment]
Drive backup is going away. Will be replaced with cloud sync
