### ISSUE TITLE
Where is my backup stored?

### ISSUE THREAD

**Issue by vikramap** [mvarnagiris/financius#116]
Hi,

I backed up my data using "BACKUP" option in Financius. 
The backup shows inside Financius. However, I don't see it in my google drive folder. Where is the backup stored?

Also, how do I change my google drive account used for backup?

Thanks.

**Comment by mvarnagiris** [comment]
This is not an issue. Backups are stored in main google drive folder. I don't think there is a way to change that without clearing apps data, but I might be wrong.

**Comment by vikramap** [comment]
Hi mvarnagiris,

Thanks for the reply. But I am not trying to change the google drive folder. 
My question is - Why can't I see the backup file in my google drive folder? 
I see backup name inside Financius, but there is nothing in my google drive folder.

Thanks.

**Comment by mvarnagiris** [comment]
Must be looking at the wrong Drive
