### ISSUE TITLE
Wrong currency sign while ruble selected

### ISSUE THREAD

**Issue by unopolar** [mvarnagiris/financius#118]
It would be great if semi-official rouble sign was used. Thanks. 
![rouble-signs](https://cloud.githubusercontent.com/assets/7408728/2805007/9286c86a-ccb1-11e3-9b2c-430c87720d79.gif)

![screenshot_2014-04-26-02-28-01](https://cloud.githubusercontent.com/assets/7408728/2804959/85c1218a-ccb0-11e3-9941-2f8f58e40c99.png)

**Comment by mvarnagiris** [comment]
You can update currency symbol to whatever you want. By default I use symbols that are provided by the system
