### ISSUE TITLE
Categories are not shown before Search action button clicked

### ISSUE THREAD

**Issue by fikr4n** [mvarnagiris/financius#119]
Steps:
    1. Click **Settings** in options menu (or maybe action overflow in other devices)
    2. Click **Categories**
Expected:
    There should be a list of categories.
Actual:
    Empty.

Steps:
    3. Click **Search** action button
Actual:
    Search `EditText` is appeared and the list of categories is also appeared.

Information:
- Sony Xperia Tipo
- Android Ice Cream Sandwich

**Comment by mvarnagiris** [comment]
Categories will not contain search any more
