### ISSUE TITLE
Pattern lock appears 2x

### ISSUE THREAD

**Issue by CamilleDufresne** [mvarnagiris/financius#122]
I think always my pattern lock appears two times. 

I have to enter it and then enter it again.

**Comment by psyren89** [comment]
Couldn't replicate this.

**Comment by supergillis** [comment]
I've been able to replicate this issue:
- Open the app;
- Do _not_ unlock the pattern lock;
- Switch to another app or home screen or just put your phone away;
- Wait a few minutes, i.e. the time after which Financius re-enables the lock?
- Open the app from the recent app list;
- Unlock;
- Unlock again!

**Comment by mvarnagiris** [comment]
Yup that might do it. Thanks. The lock won't be in the next release probably, but when I add it back I will make sure to fix this

**Comment by mvarnagiris** [comment]
Not relevant any more

**Comment by CamilleDufresne** [comment]
Well, it is still relevant. 

There is no pattern anymore, but you can enter a PIN - guess what appears 2 times from time to time? 

Absolutely identical problem.

**Comment by mvarnagiris** [comment]
If it happens, then new issue should be created with steps to reproduce
