### ISSUE TITLE
Awkward month names in Russian (maybe other langs too)

### ISSUE THREAD

**Issue by sexyhot** [mvarnagiris/financius#124]
When using Russian translation, month names are used in wrong form (e.g. "Июня" instead of "Июнь"). This looks a bit strange in most of the screens. Quick search didn't show those names in the translation file, so I think they are substituted by some Android API.

**Comment by mvarnagiris** [comment]
I will probably switch to different library for dates, so hopefully this will be fixed. Thanks for reporting

**Comment by mvarnagiris** [comment]
This will be updated in new version
