### ISSUE TITLE
Beta version: Cannot choose period with a range

### ISSUE THREAD

**Issue by kimkha** [mvarnagiris/financius#126]
I choose From date, it's OK. Then I choose To date, it remove my From date.

**Comment by kimkha** [comment]
I fixed that bug.

**Comment by mvarnagiris** [comment]
I appreaciate you contributing, but I think you should hold off for a while, because I'm working on a new version of the app on "restructure" branch

**Comment by kimkha** [comment]
ok. Can I get new branch? I cannot see it on this GitHub.

**Comment by CaioCosta** [comment]
@kimkha, @mvarnagiris merged and deleted the branch a couple of hours ago. He may correct me if I'm wrong, but that tells me he's working mainly on the dev branch now.

**Comment by kimkha** [comment]
Oh... I see... But @mvarnagiris, when will you update for beta channel on Google Play Store?

**Comment by mvarnagiris** [comment]
Yup, I've switched to dev branch. It started out as an experiment, but now I will be focusing on this new app :)

Update will come when Google releases new Android version and when I finish this app

**Comment by mvarnagiris** [comment]
This will updated in new version
