### ISSUE TITLE
Merge Transactions and Reports into a History screen

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#13]
In Financius, both the Transactions screen and the Categories report are used to check your expenses during a certain period of time. Therefore, I think it would make sense to merge them into a single History screen:

![financius history](https://f.cloud.github.com/assets/694794/1510044/e257a716-4a6f-11e3-884e-21016c2733d3.png)

Each period (be it monthly, yearly or of any other type) has a card, which shows a category pie chart by default, but can be expanded in order to also show a chronological list of transactions created during that period.

Additionally, the Transactions and Categories reports cards in the Overview should also be combined into a single Summary card, as seen here:

![financius overview](https://f.cloud.github.com/assets/694794/1510062/19cb98be-4a71-11e3-918b-86443d53b3ea.png)

**Comment by mvarnagiris** [comment]
Potentially a good idea.. :)

**Comment by frandavid100** [comment]
Glad you like it!

**Comment by assoc** [comment]
I think we must return to this suggestion.
Solution at first image is the best way to solve problem of long transactions list at "transactions" screen. Just merge screens and use cards. Please, realise 100% of this suggestion (2/3 is already done).

**Comment by verticesearestas** [comment]
+1

**Comment by mvarnagiris** [comment]
The UI has changed too much for this to be relevant
