### ISSUE TITLE
Draw Pattern can be bypassed

### ISSUE THREAD

**Issue by Karuname14** [mvarnagiris/financius#132]
Security -- App Lock - Draw Pattern

I have setup the draw pattern lock
While Opening the financious

The Draw Pattern shows, but it can be bypassed by pressing "back key" and it goes straight to Accounts "Overview"

**Comment by philipgiuliani** [comment]
I cannot reproduce this issue. When press the back key, it will close the app.

**Comment by psyren89** [comment]
I couldn't replicate this either.

**Comment by mvarnagiris** [comment]
Not relevant any more
