### ISSUE TITLE
Merge from backup

### ISSUE THREAD

**Issue by formiga90** [mvarnagiris/financius#136]
Would be nice if one can merge from different backups.

 In my case, i lost all the data on my phone and kept using financius after that, so all data was new. Today i noticed i had some backups from the time that the data on my phone was lost, so right now i have two different backups that i wanted to merge.

**Comment by mvarnagiris** [comment]
What you can do is open old and copy appropriate parts to new file and try to restore then.

**Comment by mvarnagiris** [comment]
Implemented. Can do a clean restore or restore&merge
