### ISSUE TITLE
Issue connecting to Google Drive

### ISSUE THREAD

**Issue by sam2036796** [mvarnagiris/financius#137]
Application worked great for months. Suddenly stopped connecting to Google Drive yesterday.
After clearing the app data and selecting my gmail account, it can't get past the "Enable Backup" screen.
I cleared the data again and this time selected to Add Account > Existing. Entering my email and password manually, but keep getting "Couldn't sign in. There was a problem accessing Google servers. Please try again later.".
I can sign in to Google Drive via the web, so I know the emails and password are correct.
I even tried deleting my gmail account on the phone (Setting > Accounts) and re-creating it, but that didn't work.
Also, on a side note it would be great to have an import option to allow you to import the "Your data" export into a new profile since I may have lost my backup if I can't get this to reconnect to Google Drive.
Any help would be very much appreciated.

Thanks,
sam2036796

**Comment by vikcon** [comment]
Same here. I flashed my cell and now unable to restore from Google drive. Nothing happens when I click on Google drive icon in the settings. Please fix.

Thanks
vikcon

**Comment by passy** [comment]
Not sure if this is the same thing, but I'm seeing an "Unknown issue with Google Play services." error when I try to manually backup or restore data. Did your key expire or something?

**Comment by kiransprojects** [comment]
Same as passy. Me too getting the same error "Unknown Issue with Google Play Services"!

**Comment by sureshmaathew** [comment]
Google drive Connecting and backup issue. No error message or nothing happening while backing up manually.

**Comment by winbold** [comment]
+1

Same issues for me as well.

**Comment by osvatha** [comment]
Same here, backup stopped working, after reinstall, can't connect to google drive (Enable backup button does nothing). No error message. Tried it on Android 4.4.2 on Note3 and LG G2, aosp 4.4.2 on LG G2

**Comment by davidbarredo** [comment]
+1, tried it on Android 4.3.X on Galaxy Nexus and Nexus 7, no error message.

Something new about this issue?

**Comment by mvarnagiris** [comment]
I know where the problem is. Apparently I accidentally deleted Financius project in Google Cloud :( I will create a new one and prepare a new build. Sorry for this.

**Comment by mvarnagiris** [comment]
Fixed

**Comment by winbold** [comment]
Awesome... works for me now.
