### ISSUE TITLE
Show related transactions in the same screen

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#14]
When you click a transaction on a transaction list, there's no real point in opening it on a separate screen because all its relevant data is already shown in the list.

But it could be useful to open a screen showing you all the different stances where that transaction happened, such as all the times where you refilled your gas tank or paid your phone bill. Here's a mockup showing it:

![financius transaction 1](https://f.cloud.github.com/assets/694794/1510094/77db806c-4a72-11e3-842e-d3e743596b6f.png)

Each of those instances would have one button to repeat it (which would create a new one and autofill all the fields with the relevant information) and another to revert it (which would do the same, but invert the From and To fields) in case you want to (e.g.) return an item you bought.

![financius transaction 2](https://f.cloud.github.com/assets/694794/1510108/1027c81c-4a73-11e3-8ffa-5d12926ae437.png)

**Comment by mvarnagiris** [comment]
This will be covered by Filter feature

**Comment by frandavid100** [comment]
Is Filter some kind of a search feature?

**Comment by frandavid100** [comment]
Also, is there a point to having a transaction details screen at all? After all, all the information already shows up in the transaction list.

**Comment by mvarnagiris** [comment]
Filter will act like filter :)

For consistency there is a point in having detail screen, because all other objects have detail screen
