### ISSUE TITLE
New Accounts and Account details screens

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#15]
The Accounts screen could benefit from some of the changes suggested in other issues. First off, here's a redesign with a card interface:

![financius account 1](https://f.cloud.github.com/assets/694794/1510143/1e25019a-4a74-11e3-817d-bf470fe54c8b.png)

The actionbar is used to show the total balance, and each card has one button to add an income to it, and another to add an expense.

When you click an account, you can see another screen with its details and history cards, as described on issue #13.

![financius account 2](https://f.cloud.github.com/assets/694794/1510145/4a4a8e3e-4a74-11e3-82d9-88a6a4999908.png)

**Comment by mvarnagiris** [comment]
Same issue here as I wrote somewhere else. To enter new transaction, for now it will be only one entry point. I don't think there is a need to have a dedicated button for income, as it usually happens once a month... Plus when we have recurring transactions that will be completely obsolete :)

**Comment by frandavid100** [comment]
I really don't think that making the user enter the editor and then choose the transaction type makes things any simpler for him. If Financius is going to have different editors for the different transaction types, I think that having different entry points in the relevant places would be the way to go.

However, you are right that incomes will be used much less frequently than expenses. Maybe "Create income" can be moved to the overflow menu, or even completely moved out of the Accounts screen and into the Income categories screen?

**Comment by mvarnagiris** [comment]
I still think that this just adds confusion. More options = more confusion
