### ISSUE TITLE
Updated to version 0.11.0

### ISSUE THREAD

**Issue by islandnupe** [mvarnagiris/financius#163]
The app no longer shows income on the reports screen,  it only displays expenses. Is this a deliberate change? If so, I definitely need to roll back to version 0.10.0.
I hope you can point me in the direction of the old ask. For some reason when I down load it from the app store, I only get version 0.11.0

**Comment by mvarnagiris** [comment]
You are using beta version. If you don't want a product that is not finished, you should not use beta version. To leave beta channel go to here https://play.google.com/apps/testing/com.code44.finance

Also this place is not for questions but for issues. Read here before posting https://github.com/mvarnagiris/Financius#report-a-bug-or-request-a-feature
