### ISSUE TITLE
Financius as a bill reminder

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#17]
In issue #4, a user asks for recurrent transactions. If these are implemented, Financius could be used as a bill reminder.

First, there could be an Upcoming section that shows monthly lists of recurrent transactions, such as these:

![financius repeat 2](https://f.cloud.github.com/assets/694794/1510339/9ec01836-4a7d-11e3-95c4-5f5138519791.png)

Here each card shows a month, complete with its expected balance.

When the day comes to pay a bill, Financius can act as a reminder. Due bills can appear as a card on the Overview, or even warn the user through a notification.

![financius repeat 3](https://f.cloud.github.com/assets/694794/1510349/155f8f44-4a7e-11e3-831f-6612d4800829.png)

That card would have two buttons, one to delay the notification (in case you haven't paid it yet and don't want to be reminded yet) and the other to confirm the transaction.

For variable bills (those that can change from one month to the next) it would be useful to allow the user to leave the Amount field empty, so that he can fill it later when he confirms the transaction.

**Comment by mvarnagiris** [comment]
Recurring transactions will cover this feature

**Comment by frandavid100** [comment]
Recurring transactions are necessary for this to work, but I think this complements them nicely.

For example, if it's an expense you have to manually go and pay (e.g. some landowners demand that you pay them in cash) Financius can actually remind you to do it, instead of simply assume that you did and mark it as paid when you might have forgotten to pay it.

Some other transactions (e.g. the phone bill) happen each month but don't always involve the same amount of money, so it's necessary to have a little manual feedback from the user.

**Comment by mvarnagiris** [comment]
Recurring transactions would not mark transactions as confirmed. THey would all be pending. User will have to confirm all of them manually

**Comment by frandavid100** [comment]
Well, this is basically an interface proposal for that. Is it possible to merge this issue and #4 ir order to discuss them together, since they're really the same?
