### ISSUE TITLE
[updated] Crash at transaction list

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#182]
I have a lot transactions (just long list). Collapse one month and then try to scroll down. If you collapse more months (>8) app crashes 'faster'.
[Database](https://drive.google.com/file/d/0B5i82Y4dtZg-YV83QWRLTGNxckk/view?usp=sharing)

**Comment by assoc** [comment]
Also crashes at any different period: week, year and day.

**Comment by mvarnagiris** [comment]
Have you send crash report?

**Comment by assoc** [comment]
Sorry, sent now

**Comment by mvarnagiris** [comment]
Thanks. I see it. Will fix it

**Comment by mvarnagiris** [comment]
Interesting issue. Could you send me your backup json file? If you don't want to do that, what would really helpful is if you make a backup, open it, find a transaction that has "model_state": 0 and post that item here. If that doesn't make sense, let me know I'll try to explain it a bit better.

**Comment by assoc** [comment]
Possibly, this is not depends on collapsed items.
There is no items with model_state=0 in json or database (checked by copying to PC). Backup fails every time. I think db was damaged.

**Comment by mvarnagiris** [comment]
That's not good :/ Does it say why backup fails? If it crashes, make sure to send a crash report

**Comment by mvarnagiris** [comment]
Actually it seems that there is a problem with categories. Try to search for a category that has model state as 0 or empty or null

**Comment by assoc** [comment]
No crashes at backup, but file is not full (only part).
All model states are 1.

**Comment by mvarnagiris** [comment]
There is't much I can tell without looking at the actual backup file

**Comment by mvarnagiris** [comment]
Cannot reproduce this. So closing

**Comment by assoc** [comment]
Sorry for delay, but [here](https://drive.google.com/file/d/0B5i82Y4dtZg-YV83QWRLTGNxckk/view?usp=sharing) is simplified (changed amounts) model of my db. Still crashes at sep/oct 2013

**Comment by mvarnagiris** [comment]
Thanks for the database. That will help me find the issue.

**Comment by mvarnagiris** [comment]
By the way, does that crash still happen with the latest version?

**Comment by assoc** [comment]
Version 0.12.1 - crash.

**Comment by assoc** [comment]
Problem was resolved. I checked all database and found incorrect category at transaction item id=61 (doesn't exists). Now backup and restore function works, but there are no message like "backup done" and it's confusing.
(There are some lags at >500 transactions collapsed by month or week. Maybe RecyclerView?)
