### ISSUE TITLE
Smaller left panel

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#184]
I mean height. May be like material Play Store? Also with options menu on this panel (without 'points').

**Comment by mvarnagiris** [comment]
I don't think Google has finalized the guidelines for this

**Comment by philipgiuliani** [comment]
I just found the following document!

https://developer.android.com/design/patterns/navigation-drawer.html#Checklist
- The **action bar remains in place** and adjusts its content.
- Your navigation drawer **overlays the content**.

It not fixed that it should ONLY overlay the content, but they showed its also in the images below the navigation bar.

**Comment by mvarnagiris** [comment]
It's outdated. 

This is new http://android-developers.blogspot.co.uk/2014/10/material-design-on-android-checklist.html

**Comment by philipgiuliani** [comment]
Sorry you are right. I just noticed that the recent updates have the draver covering the action bar.

Google Inbox 1.1 Changelog
- bigger slide-out navigation that goes over the action bar
