### ISSUE TITLE
Set the application label when backing up on Google Drive

### ISSUE THREAD

**Issue by virgiliu** [mvarnagiris/financius#186]
In Google Drive's connected apps Financius appears as "Project Default Service Account". This can cause some confusion.

To reproduce this I went to Google Drive's connected apps, removed "Project Default Service Account". Then in Financius I tried to create a backup on Google Drive. This led to the application requesting permissions again. After granting access "Project Default Service Account" appeared again in the connected apps and thus I came to the conclusion that in this case it was Financius.

**Comment by mvarnagiris** [comment]
I'm not quite sure but it seems that this issue could be resolved by updating app engine. Will look into it, thanks for reporting

**Comment by mvarnagiris** [comment]
Yeah that name was in there. I've changed it to "Financius".
