### ISSUE TITLE
Show balance card last, allow the user to hide it from the Overview

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#19]
Among all the potential cards shown in the Overview (Summary of the month, Lendings, Due transactions and so on) Balance in the most static one (meaning, it won't probably change a lot from one month to the next) and the one that could give the most sensible information to someone peeking over your shoulder while you open the app to create a transaction.

Therefore, I think it should be moved to the bottom and there should be an option to entirely hide it from the overview. Would that be OK?

**Comment by mvarnagiris** [comment]
Moving to the bottom doesn't guarantee that it will not be visible. And the order of the cards potentially can be in any order.

**Comment by frandavid100** [comment]
Well, there are two separate issues concerning Balance.

One is relevance, the fact that other cards like Summary might be more interesting to see. That's why I'd like to show those before.

The other is privacy, the fact that it can give out private information to anyone watching the screen. That's why I'd like a setting to not show it in the Overview at all.

**Comment by mvarnagiris** [comment]
I'd say that balance is more interesting to see on the phone rather that summary, because when you're on the go, you don't analyze data, but you might want to check how much cash you have

**Comment by frandavid100** [comment]
I guess it depends on what particular account you're thinking about. When you're abroad and you've taken with you a specific amount of cash, it's useful to keep track of how much you have left. But on the other hand I'm not usually interested in checking out how much money I have on my bank account, because day-to-day transactions don't usually affect it all that much. It always stays pretty much the same.

Maybe the app could decide how relevant the card is depending on whether there have been important movements in specific accounts. If you have 200 € in your Cash account and you spend 20 you're making a relevant decrease in that account, so it makes sense for the app to warn you that you only have 180 left. But if you have 20.000 € in your bank account and you spend 20, that barely affects its balance.

Maybe the first example should push the card to the top, but the second one shouldn't.

As for the second issue, privacy. I think you should be able to open Financius in order to create a transaction, without everyone seeing how much money you have in the bank. Right now Financius protects your information with the unlock pattern, but that also keeps you from operating it.

Maybe it would be useful to be able to tell the app when it needs to ask you for the pattern: never, in order to see your balance, or when opening the app. If you select "in order to see your balance" you would still be able to add incomes and expenses, but the Balance card wouldn't be shown at all and you would be asked for the pattern in order to open the Balance or to see an account.
