### ISSUE TITLE
Order tags by usage

### ISSUE THREAD

**Issue by philipgiuliani** [mvarnagiris/financius#191]
It would be very awesome if the tags could be ordered by the usage, so in a normal case i would be much faster (what is very important for a finance manager) to create a transaction. In a larger list its difficult to find the tags i want.

**Comment by mvarnagiris** [comment]
Yeah tag selection is note very nice now and has to be improved

**Comment by philipgiuliani** [comment]
A select tag like this would be nice! :) That would be really the fastest way! https://github.com/splitwise/TokenAutoComplete

**Comment by mvarnagiris** [comment]
It will be like that

**Comment by philipgiuliani** [comment]
Amazing! Thanks for your work :boom:

**Comment by ghost** [comment]
Do you have a rough estimate for when the tagging system will be updated? It's extremely hard to tag my finances at the moment. Have you considered doing like a sort of subcategory type thing with the tags? Such as parent and child tags? Look into how evernote does tagging. It's great. Here's an article explaining some of the things you can do. Really makes it easy to sort through thingshttp://michaelhyatt.com/evernote-tags.html

**Comment by mvarnagiris** [comment]
First I'm gonna improve transaction auto complete feature See how that goes. Maybe you won't have to select those tags at all, cause correct tags will be preselected for you. After that I will improve tag selection

**Comment by mvarnagiris** [comment]
#276 #279
