### ISSUE TITLE
JSON backup /restore to Google Drive visible folder

### ISSUE THREAD

**Issue by mvarnagiris** [mvarnagiris/financius#2]

**Comment by ghost** [comment]
Will this feature be provided anytime soon? I would love this feature. I like having the freedom of being able to backup my file anywhere I see fit. Currently, we cannot see or download the file from our Google Drive AppData folder.

Thanks, I adore the app so far. Liquid smooth.

**Comment by mvarnagiris** [comment]
Backup and restore to any Google Drive folder implemented
