### ISSUE TITLE
MainActivity loses title after rotation

### ISSUE THREAD

**Issue by mvarnagiris** [mvarnagiris/financius#200]

**Comment by i906** [comment]
Instead of setting the title in `onNavigationItemSelected`, why not each fragments set their own titles?, e.g. 

``` java
((BaseActivity) getActivity()).getSupportActionBar().setTitle(R.string.overview);
```

**Comment by mvarnagiris** [comment]
It used to do that :) I was cleaning up the code and removed it. But letting fragments set their own title only works on phone. What if you show multiple fragments on a tablet?

**Comment by i906** [comment]
I see, I haven't encountered that kind of situation before. Perhaps the titles can be set based on the current/available fragments in the activity?

**Comment by mvarnagiris** [comment]
Yeah, so basically Activity needs to decide on a title. I think current implementation is fine for now. I'll just save title to instance state and restore it after rotation

**Comment by mvarnagiris** [comment]
I think it would make sense to switch from using fragments to using Activities + custom views. That way you can have better control over toolbar hat is controlled by and Activity. Now I need to put in either layout hacks or a lot of boilerplate code

**Comment by mvarnagiris** [comment]
Fixed
