### ISSUE TITLE
Acount Balance calculation after edititing transaction

### ISSUE THREAD

**Issue by ghost** [mvarnagiris/financius#205]
I've noticed that after I completely entered a transaction and alter the account this transaction was payed from later, the amount gets taken from the new account (just how its supposed to do) but it does not get added back to former account. So finally the amount gets "payed" twice after the transaction is altered.

**Comment by mvarnagiris** [comment]
I'm aware of this. It might have already been fixed. I'll check

**Comment by mvarnagiris** [comment]
Fixed
