### ISSUE TITLE
Timezone is not updated

### ISSUE THREAD

**Issue by areisp** [mvarnagiris/financius#211]
Oct 26 timezone Europe/Moscow was changed from UTC+4 to UTC+3. I guess this app still uses old one or something like that.
![screenshot_2014-11-03-10-34-53](https://cloud.githubusercontent.com/assets/5154362/4879561/1343d5da-632d-11e4-90b1-df45cabf13a5.png)

**Comment by mvarnagiris** [comment]
Cannot reproduce. If someone can reproduce please let me know which time zone you are trying. For now I will remove it from milestone.
