### ISSUE TITLE
Moving backward and forward on detail screen

### ISSUE THREAD

**Issue by jeavilez** [mvarnagiris/financius#213]
Dear Mantas,
When detail screen is displayed, it is not possible to move backward or forward to the next transaction.

**Comment by mvarnagiris** [comment]
Do you mean swipe left\right or something else?

**Comment by jeavilez** [comment]
Exactly, you've got it.

**Comment by mvarnagiris** [comment]
I see. Well that's not happening because of reasons. UX related reasons. And implementation related reasons
