### ISSUE TITLE
Remove Main/Sub Category

### ISSUE THREAD

**Issue by lokmancetin** [mvarnagiris/financius#217]
Default Main/Sub Category and also Additional categories that users added in time should have ability to remove. 
A recycle bin may appear on Long Touch/Click action.(which is activate move sub/main categories)  
Thank you for your support.

**Comment by mvarnagiris** [comment]
You can already remove everything you want

**Comment by lokmancetin** [comment]
Then somebody tell me how to remove garbage and recycling.  I couldnt find any option for that

**Comment by mvarnagiris** [comment]
You either need to click overflow button (three dots) in top right or press a menu button on your phone while you are in category details screen
