### ISSUE TITLE
Edit transaction screen

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#235]
Possible concept was found nearby :)
[Image](http://i.imgur.com/zI3fOFB.png)

Type of transaction is defined by "select category" dialog (like "categories" screen in settings, with divided expenses/income categories), and last item in this list is "transfer".
Red area is dynamic and not visible by default (it is for income and transfer).
And no time.

**Comment by mvarnagiris** [comment]
Category does not define transaction type any more, because category is not mandatory field
