### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by kerkrisz** [mvarnagiris/financius#240]
Hi,

This main and subcategory in the new version is a bit difficult, because I can choose all subcategory in every main category. This is uncomfortable :( Are you planning that you create back the old category system? I really love this app, I use this every day all the time.
Thanks,

Kerkrisz

**Comment by mvarnagiris** [comment]
Sub categories are not coming back. Also, it would be best if general questions would be asked in G+ community. Github is only for tasks/bugs
