### ISSUE TITLE
Exchange rate is cropped when less then 1/2000

### ISSUE THREAD

**Issue by madhead** [mvarnagiris/financius#242]
Here, in Belarus we have pretty high exchange rates. At the moment I write this lines, one euro costs 13860 rubles. And when I try to input exchange rate using arithmetic operations it is rounded to zero. Looks like every exchange rate that is less then 1 / 2000 is treated as zero (1 / 1999 gives 0.001). Can you please add more precision? In previous versions of Financius this worked fine.

**Comment by mvarnagiris** [comment]
#241 It's literally previously reported issue. Aren't these the same?
