### ISSUE TITLE
Feauture: Transaction List per Category

### ISSUE THREAD

**Issue by uppr90allday** [mvarnagiris/financius#244]
Request feature where when you click on the reports tab, and click on a category such as Food, Leisure, Transportation, etc. a list of all the transactions in that category will show up for the month. Just like the transactions list itself, but organized by category for each month, year, day etc.

**Comment by uppr90allday** [comment]
Also an Auto Save feature, where the app saves it to the same folder on an SD drive or the phones drive.

**Comment by mvarnagiris** [comment]
#20 Duplicate
