### ISSUE TITLE
Balance reduction despite not including in report

### ISSUE THREAD

**Issue by MaybeThisIsRu** [mvarnagiris/financius#253]
I added an expense for my 'bank' account, and asked it not to be included in the reports. While it did not add to my monthly expenses report, it deducted the balance from my 'bank' account anyway.

I'm not sure if this was intended. If it was, could an option be added where you add an expense that is neither included in the monthly report nor causes a balance reduction?

**Comment by mvarnagiris** [comment]
This is working as intended. If you don't want your transaction to affect accounts, then make it pending
