### ISSUE TITLE
Accounts: Arrange the order in which they are shown.

### ISSUE THREAD

**Issue by MaybeThisIsRu** [mvarnagiris/financius#254]
On the home page and the accounts page, all the accounts are shown. At the moment, we cannot arrange in the order they are shown.

For example, if I have four accounts: Bank, Wallet, Savings and Example Private Limited. Now, I would like to see my wallet and bank account first, followed by my savings and my company account.

I can't achieve this right now.

**Comment by mvarnagiris** [comment]
#273

**Comment by MaybeThisIsRu** [comment]
These two are not the same.

My suggestion is to let one pick the order in which the accounts appear on the Accounts tab, as well as the Overview tab, while the other suggestion is to predict the account most used with a particular transaction and show that as the top suggestion while adding a new transaction.
