### ISSUE TITLE
Backup to Google Drive not working

### ISSUE THREAD

**Issue by talentedunicorn** [mvarnagiris/financius#256]
**Device**: HTC M8
**OS**: Android 4.4.4

When attempting to use Backup to Google drive I get a flickering log in screen and the app gets stuck there.

**Comment by mvarnagiris** [comment]
Not a lot I can do with this information. Could you post a video or something? It sounds like a Google Drive problem.

**Comment by talentedunicorn** [comment]
Here's what I get the alternation flicker of these two images, might be a Drive problem but the Drive app works fine
![2014-11-30 11 28 29](https://cloud.githubusercontent.com/assets/904501/5237559/80cc9cb8-78c7-11e4-9aa7-cd75aa4e295f.png)
![2014-11-30 11 28 33](https://cloud.githubusercontent.com/assets/904501/5237560/84fcc682-78c7-11e4-96ce-d46970b2322b.png)

**Comment by mvarnagiris** [comment]
If signing in screen keeps coming on, then it must be drive problem.

**Comment by talentedunicorn** [comment]
Cool, thanks I guess I should close this.

**Comment by mvarnagiris** [comment]
If you could find another app that does google drive integration and see if it works for you that would be great

**Comment by S-eye** [comment]
I have the same problem on Moto G XT1032, Android 4.4.4.  Google Drive works fine with ES File Explorer.

Edit: It happens on Android 5.0.2 also

**Comment by mvarnagiris** [comment]
Related #320
