### ISSUE TITLE
Need income manager

### ISSUE THREAD

**Issue by enseeyes** [mvarnagiris/financius#259]
Hi,

Th app is simply superb. But one feature what it lacks is the income manager. this helps in tracking both income and expenses #newFeature

**Comment by mvarnagiris** [comment]
What do you mean by income manager?

**Comment by enseeyes** [comment]
Similar to the expense section in the reports page, where we can get to know how much is the income for each month.

**Comment by mvarnagiris** [comment]
Ah I see. Yes, that is necessary

**Comment by mvarnagiris** [comment]
#280
