### ISSUE TITLE
Pending amount is not calculated in transactions list

### ISSUE THREAD

**Issue by TheNephilim88** [mvarnagiris/financius#260]
In transaction section there are only expenses calculated.

What I think will make more sense or is better is to calculate pending expenses, too.

It also would be nice if focus is not just on expenses. Better to show both expenses and incomes in those headers (Pending, December....).

**Comment by mvarnagiris** [comment]
Yup I agree. We need better reports

**Comment by mvarnagiris** [comment]
Actually, they are calculated

**Comment by TheNephilim88** [comment]
Attached you will find screenshot of version 0.17.0, so you may see what I meant.

In the transaction list @ pending are movements, incomes and expenses, but in the current version there is not calculated any sum of this, just showing "Pending 0.00 €"

![screenshot_2015-01-05-11-31-26](https://cloud.githubusercontent.com/assets/1174584/5612021/b1f04772-94ce-11e4-9603-f9544aa43ee9.png)

**Comment by mvarnagiris** [comment]
They're all transfers on income. Only expenses are calculated

**Comment by reneph** [comment]
Wrong, the most bottom (7th January) is an expense. There are also 3 further expenses below 7th January that are under "Pending".

**Comment by TheNephilim88** [comment]
Okay, I tried around, my mistake was not checking "show in reports". Didnt knew that "show in reports" also apply to transaction-view. Nonetheless, thanks.
