### ISSUE TITLE
Can not set password. Please add "Set" button

### ISSUE THREAD

**Issue by NazarKozar** [mvarnagiris/financius#262]
"Done" button does not work. 
Please add button right after PIN field. Thanks.

![screenshot_2014-12-20-21-50-58](https://cloud.githubusercontent.com/assets/2816997/5516101/d01878b6-8892-11e4-9c1c-054c72b4e344.png)

**Comment by mvarnagiris** [comment]
Working as intended. PIN code needs to be 4 digits. Once you enter 4 digits, then it will automatically save

**Comment by NazarKozar** [comment]
Yep, I was wrong. Thanks
