### ISSUE TITLE
Account money split as cash and card

### ISSUE THREAD

**Issue by karthi20a** [mvarnagiris/financius#265]
Hi,
I have a suggestion on the accounts handled. 
The money entered for an account can be split as cash and card. As people hold cash in their hand and also do card transactions. 
By default expenses could be deducted from cash held.
when we perform an ATM transaction the corresponding amount can be transferred from card group to cash group( like income to cash group). 
Card transactions could also be entered as a part of expense and income can also be entered in card group.

Please look into the suggestion above and let me know what you think.

**Comment by mvarnagiris** [comment]
I did not understand this suggestion. Could you please clarify?

**Comment by cernicc** [comment]
I think he means that he would like to have cash money separate from other accounts. But i guess you can always create new acc and name it Cash.

**Comment by mvarnagiris** [comment]
Yup that is how you should do it
