### ISSUE TITLE
Turkish localisation should use comma (,) as decimal separator, and period (.) as thousand separator

### ISSUE THREAD

**Issue by bitigchi** [mvarnagiris/financius#266]
Unlike English (or other localisations), in Turkish, decimals are separated by comma, not period.

And thousand separator is period (.), not comma

It would be nice to fix this in a future release, both in number entry pad, and in the other fields as well.

If any assistance needed, please do not hesitate to contact me.

**Comment by mvarnagiris** [comment]
Hi Emir,

In settings you can set up your currency to use any separator you want

**Comment by bitigchi** [comment]
Hello,

Sorry for the noise, my bad. Just realised that one. 

By the way, app is great, very nice design, and nice typography.
