### ISSUE TITLE
Import duplicated categories

### ISSUE THREAD

**Issue by rtfpessoa** [mvarnagiris/financius#267]
I was trying to sync my devices and I did a backup to GoogleDrive and then I restored that same backup in my tablet.

After that my tablet had all the categories duplicated.

Is it just me or is this a bug?

**Comment by mvarnagiris** [comment]
Hi Rodrigo,

If you restore on a fresh install, then you need to do clean restore.

**Comment by rtfpessoa** [comment]
Ok, thanks for the response.

Note: Maybe you could ease the process by giving some kind of unique id to the categories especially the default ones.

**Comment by mvarnagiris** [comment]
I thought about it but it's more complicated than that. I will try to come
up with a better process for that
