### ISSUE TITLE
Pie chart problem in Report view

### ISSUE THREAD

**Issue by JokerQyou** [mvarnagiris/financius#325]
Financius version 0.17.1 (Last updated January 5, 2015) on Moto G (XT 1032) with Andoird 4.4.4 .
The pie chart in Report view some sometimes looks weird. (See the images below)
This does not happen continuously, for example, if if January 2015 is okay, and December 2014 is having problem, then November 2014 is quite possible to be okay, but October 2014 is quite possible to have this problem. Most of the time it goes like so. 
Screenshots below. 
![screenshot_2015-01-09-10-16-47](https://cloud.githubusercontent.com/assets/1465267/5674784/b6bf2ec4-97eb-11e4-8ec5-d623fbb3e0ae.png)
![screenshot_2015-01-09-10-16-51](https://cloud.githubusercontent.com/assets/1465267/5674785/b6ee2904-97eb-11e4-83c5-ee64e1dd38f4.png)

**Comment by mvarnagiris** [comment]
I will be changing the pie chart soon so this should be fixed

**Comment by mvarnagiris** [comment]
This should be fixed
