### ISSUE TITLE
Let users duplicate transactions

### ISSUE THREAD

**Issue by LeartS** [mvarnagiris/financius#335]
There are a lot of recurrent transactions in every day life: public transport every month, coffee every morning, subscriptions... these tend to be always the same, the only thing changing is the date.
So i propose a duplicate feature (maybe a button to add in the header bar of a transaction, next to the edit button) that duplicates it, leaving all the fields the same, changing only the date to the current one. Then obviously if the user wants he can quickly edit other fields.

This way you can quickly create new transactions by using old similar (or equal) ones as templates.

**Comment by mvarnagiris** [comment]
Duplicate #4
