### ISSUE TITLE
Gladle build finished with 1 error

### ISSUE THREAD

**Issue by Kalyz** [mvarnagiris/financius#340]
Information:Gradle tasks [:financius:assembleDebug]
:backend:appengineDownloadSdk
:common:compileJava UP-TO-DATE
:common:processResources UP-TO-DATE
:common:classes UP-TO-DATE
:common:jar UP-TO-DATE
:backend:compileJava UP-TO-DATE
:backend:processResources UP-TO-DATE
:backend:classes UP-TO-DATE
:backend:appengineEndpointsGetClientLibs UP-TO-DATE
:backend:appengineEndpointsExpandClientLibs UP-TO-DATE
:backend:compileEndpointsSrcJava UP-TO-DATE
:backend:processEndpointsSrcResources UP-TO-DATE
:backend:endpointsSrcClasses UP-TO-DATE
:backend:_appengineEndpointsAndroidArtifact UP-TO-DATE
:financius:preBuild
:financius:preDebugBuild
:financius:checkDebugManifest
:financius:preReleaseBuild
:financius:prepareComAndroidSupportAppcompatV72103Library UP-TO-DATE
:financius:prepareComAndroidSupportCardviewV72103Library UP-TO-DATE
:financius:prepareComAndroidSupportRecyclerviewV72103Library UP-TO-DATE
:financius:prepareComAndroidSupportSupportV132000Library UP-TO-DATE
:financius:prepareComAndroidSupportSupportV42103Library UP-TO-DATE
:financius:prepareComAstuetzPagerslidingtabstrip101Library UP-TO-DATE
:financius:prepareComGithubCastorflexSmoothprogressbarLibrary100Library UP-TO-DATE
:financius:prepareComGithubCastorflexSmoothprogressbarLibraryCircular100Library UP-TO-DATE
:financius:prepareComGoogleAndroidGmsPlayServicesBase6587Library UP-TO-DATE
:financius:prepareComGoogleAndroidGmsPlayServicesDrive6587Library UP-TO-DATE
:financius:prepareComGoogleAndroidGmsPlayServicesPlus6587Library UP-TO-DATE
:financius:prepareComJakewhartonHugoHugoRuntime110Library UP-TO-DATE
:financius:prepareComLarswerkmanHoloColorPicker14Library UP-TO-DATE
:financius:prepareComNononsenseappsFilepicker113Library UP-TO-DATE
:financius:prepareHellochartsLibrary13Library UP-TO-DATE
:financius:prepareMeGrantlandAutofittextview021SNAPSHOTLibrary UP-TO-DATE
:financius:prepareNetDanlewAndroidJoda240Library UP-TO-DATE
:financius:prepareSeEmilsjolanderStickylistheaders250Library UP-TO-DATE
:financius:prepareDebugDependencies
:financius:compileDebugAidl UP-TO-DATE
:financius:compileDebugRenderscript UP-TO-DATE
:financius:generateDebugBuildConfig
:financius:generateDebugAssets UP-TO-DATE
:financius:mergeDebugAssets UP-TO-DATE
:financius:processDebugManifest UP-TO-DATE
:financius:crashlyticsCleanupResourcesDebug
:financius:crashlyticsUploadStoredDeobsDebug
:financius:crashlyticsGenerateResourcesDebug
:financius:generateDebugResValues UP-TO-DATE
:financius:generateDebugResources UP-TO-DATE
:financius:mergeDebugResources
:financius:processDebugResources
:financius:generateDebugSources

:financius:compileDebugJava FAILED
Error:Execution failed for task ':financius:compileDebugJava'.

> java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.ExecutableElement
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> <a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> <a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

Information:BUILD FAILED
Information:Total time: 11.93 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by mvarnagiris** [comment]
Project is just in a state where it's not building
