### ISSUE TITLE
Allow negative expenses 

### ISSUE THREAD

**Issue by patcon** [mvarnagiris/financius#341]
This solves the issue when paying for a full table of diners on credit card, and accepting cash from them (into a cash account). Currently, if you want 1) for the actual billed amount to be in financius for later reconciliation, and 2) to see reports properly reflect expenses -- there does not seem to be a way to do that.

This could be solved by allowing refunds to be expressed as negative expenses. The positive cash amount could then be added to the cash account with a custom category that we can ignore from reports. Other software like quicken had allowed negative expenses in the past fwiw

**Comment by mvarnagiris** [comment]
No that's not happening. Negative expenses doesn't make sense to me. It might solve a problem, but the complications it brings are just not worth it.

**Comment by patcon** [comment]
Sorry, then how do refunds work? Like how do you ever bring a report category summation down, since categories for expenses and income are separate?

**Comment by mvarnagiris** [comment]
Make an expense of an amount you've actually paid. Then a transfer from your credit card to cash of an amount your friends gave to you.

**Comment by patcon** [comment]
Sorry? I don't think that solves the issue:
- Expense dinner on CARD: $80 (categorized as "food")
- Transfer $60 from CARD to CASH (no categories, decided in #64)
- End of month, balances are correct, but my summary report shows +$80 spent on food, when I actually spent $20, so the beautiful graphs are not helpful

Am I missing something? Your solution doesn't appear to address the concern. And obviously, thanks for your consideration on this.

**Comment by mvarnagiris** [comment]
Your expense should be $20

**Comment by patcon** [comment]
That was not your original suggestion, so I assume you didn't realize what I meant when you first declined. I stand by the fact that the latest suggestion is an awkward solution, and makes reconciliation of statements awkward as line items don't match the records. Anyhow, if I need this and you feel strongly that other financial tracking software is doing it wrong, then I suppose I can roll my own apk. Thanks
