### ISSUE TITLE
Currency rates not updated.

### ISSUE THREAD

**Issue by olenchenko** [mvarnagiris/financius#346]
Hi.

First of all I wanted to thank you for great application.
I have an issue updating currency rates - its not working manually or automatically (every day).
Its started after update to version 0.18.0, it was working in 0.17.1.

Thanks

**Comment by mvarnagiris** [comment]
This is fixed. I just published a new version

**Comment by olenchenko** [comment]
Sorry I was a bit late.
Started to write this issue before you fixed it and updated changelog.

**Comment by mvarnagiris** [comment]
No worries :)
