### ISSUE TITLE
Split transactions

### ISSUE THREAD

**Issue by mvarnagiris** [mvarnagiris/financius#35]

**Comment by jeavilez** [comment]
There should be some way of recording a transaction in which the funds come from different accounts and / or to be assigned to different categories.

**Comment by mvarnagiris** [comment]
With different categories I agree, but different accounts would make it two different transactions.

**Comment by jeavilez** [comment]
Thanks for the answer. About the comment, I think a transaction could be paid with different accounts, given that the payee may accept diferent kinds of payments (for example cash and credit card in one purchase), and do not necessarily got specifically identified the goods payed for (for example: groceries), but the act of buying which originates the transaction is only one. If you consider it ok, it would be fine.

**Comment by mvarnagiris** [comment]
Hmm interesting point. I will need to consider this when I come to implementing this feature

**Comment by Oscaruzzo** [comment]
Another example is if you go to the restaurant with a friend. You pay for both with your credit card and he gives you his part in cash.

Let's sat you spend 20 and he spends 30. So you have 

-50 from your credit card (account)
+20 in expenses, category "food"
+30 in your wallett (account).

**Comment by mvarnagiris** [comment]
I think this feature would overcomplicate things too much for this app

**Comment by patcon** [comment]
+1 to split transactions fwiw.

Use-case is when you pay your party's bill on your card, and other payers give you cash in hand for their portion. You want your part to be categorized appropriately (and be in reports), but the portion covered by cash to be uncategorized. Not sure how the underlying data is structured, but my thought was that perhaps it would make sense to store these as mulitple transactions, but just use the UI/view to merge those multiple transactions via a common "transaction hash" field. Export to CSV would show them all separate.
