### ISSUE TITLE
Multiple tags problem

### ISSUE THREAD

**Issue by levlist** [mvarnagiris/financius#351]
Hi,

If I add multple tag to an entry, that element is showing up in the report in that category multiple times.
It can be mislead.

The added element:
![multiple_tag_entry](https://cloud.githubusercontent.com/assets/10905822/6095862/35809f48-af72-11e4-8b8e-5f1f8575c2b4.png)

Portion of report by category:
![multiple_tag_in_report](https://cloud.githubusercontent.com/assets/10905822/6095863/4f21c238-af72-11e4-83c4-45d651569761.png)

Thanks

**Comment by levlist** [comment]
Sorry about I didn't use English version, but I didn't want to change my global language settings.
That's why I suggested to language changing possibility (Ticket No: #350)
Thanks

**Comment by mvarnagiris** [comment]
How else can they be displayed? If you want them to be as one, then you should use one tag instead of two. What if you play more ports than squash? How else would you know how much you spend on sports in total and how much on each sport separately.

**Comment by levlist** [comment]
OK, I understand your exact concept now.
I used multiple tagging, because if later filters or some reports become available, you can filter your costs or displaying charts by tags (sport, squash, futsal, etc.)
Thanks for your answer!
