### ISSUE TITLE
Currencies are not being updated v 0.18.5

### ISSUE THREAD

**Issue by LS-Myron** [mvarnagiris/financius#353]
Hi :),

I want to thank you for making this app :). I like the app very much, its very handy.
But the currencies are not updated anymore when refresh, it stays at 1.0.

Financius - Version 0.18.5
HTC one X
Lollipop rom

**Comment by Myron-Biker** [comment]
Sorry Lekke

**Comment by LS-Myron** [comment]
Sorry I had to remove my cache and data from the app and reimport the backup. Its working now. Sorry for the inconvenience :O.
