### ISSUE TITLE
Locking issues

### ISSUE THREAD

**Issue by kNNN** [mvarnagiris/financius#355]
Sometimes I have issues with entering PIN for unlocking serveral times, even so PIN was correct. In other cases, when I close the app and reopen it again, I manage to get in without entering PIN. This worked really nice before the last update, locking and unlocking with PIN.

**Comment by mvarnagiris** [comment]
You will have to provide steps to reproduce this unlock issue.

As for going into the app without unlocking - there is a 5 second interval when you can come back to the app without unlocking it again
