### ISSUE TITLE
Transactions getting undeleted 

### ISSUE THREAD

**Issue by julianotoriani** [mvarnagiris/financius#356]
Canceling deletion of an account makes deleted transactions come back. 
Version: 0.18.7

Steps to reproduce from scratch:

1 - Create an account with a $100 balance.
2 - Add a $100 confirmed expense of any kind associated to that account (now the account balance is zero)
3 - Delete the transaction you just created (account balance is back to $100)
4 - Go to accounts, select the account
5 - Touch "Delete" on the menu, will show the confirmation dialog
6 - Press "Cancel" or back button to dismiss the dialog

Done, now that $100 deleted expense is back and the balance is zero again.

**Comment by mvarnagiris** [comment]
Thanks for good bug report. It was easy to reproduce. I fixed it.
