### ISSUE TITLE
Importing creates duplicate currencies 

### ISSUE THREAD

**Issue by tsangiotis** [mvarnagiris/financius#372]
Here is the currencies screen after the import

![screenshot_2015-03-17-13-18-20](https://cloud.githubusercontent.com/assets/697354/6686188/995b9bc8-cca8-11e4-90eb-0c3ac359827c.png)

**Comment by tsangiotis** [comment]
The same problem exists with categories.

**Comment by mvarnagiris** [comment]
If you want to avoid duplicates, you need to do clear and restore. This will delete all current data and only import what's in the backup. Otherwise there is no way to avoid duplicates, as the IDs generated for items are different on different devices
