### ISSUE TITLE
Invisible buttons on "Backup" screen

### ISSUE THREAD

**Issue by madhead** [mvarnagiris/financius#385]
Import button is invisble on "Backup" screen on my Sony Xperia S (LT26i, 4.3" 720x1280, Android 4.1.2). See screenshot. Landscape mode is affected too.

![screenshot_2015-05-13-15-05-57](https://cloud.githubusercontent.com/assets/577360/7610022/ff37925c-f981-11e4-80fa-f57fe08c6a9f.png)

**Comment by SimonErle** [comment]
hello i have the same problem. I just noticed that the recovery is available if you are not logged in. I find that connecting with google is stopped in July.
