### ISSUE TITLE
The show transaction change transaction on edit date

### ISSUE THREAD

**Issue by walter-juan** [mvarnagiris/financius#39]
I explain with example:

I have two transactions one at date 19 and other at date 18 in same month.
I go in list of transactions and click on transaction of date 19, now I'm in show of transaction, click on edit, **I change the date from 19 to 17 and save**. After save return automatically in show but **the the show view is refreshed and changed for other transaction**, the transaction of date 18.

**Comment by mvarnagiris** [comment]
Ah yeas. I knew about this. But it's good that you've written it here. Because I have already forgotten about it :)

**Comment by mvarnagiris** [comment]
Fixed by removing the ability to swipe between item details
