### ISSUE TITLE
Broken conversion rates

### ISSUE THREAD

**Issue by madhead** [mvarnagiris/financius#397]
Not sure this will be addressed, the project looks abandoned.

Last year's devaluation totally ruined our currency (BYR) and now one EUR / USD cost more than 20K BYRs. Yahoo cannot handle such rates:

```
select * from yahoo.finance.xchange where pair in ("BYREUR","BYRUSD")

{
 "query": {
  "count": 2,
  "created": "2016-02-03T22:50:23Z",
  "lang": "en-US",
  "results": {
   "rate": [
    {
     "id": "BYREUR",
     "Name": "BYR/EUR",
     "Rate": "0.0000",
     "Date": "2/3/2016",
     "Time": "10:50pm",
     "Ask": "0.0000",
     "Bid": "0.0000"
    },
    {
     "id": "BYRUSD",
     "Name": "BYR/USD",
     "Rate": "0.0000",
     "Date": "2/3/2016",
     "Time": "10:49pm",
     "Ask": "0.0000",
     "Bid": "0.0000"
    }
   ]
  }
 }
}
```

As you see, the rate is zero. Due to this fact currency conversion is totally broken in Financius. It would be great to have an ability to enter them manually...

**Comment by madhead** [comment]
Workaround that seems to work for rooted phones:
1. Install `sqlite3` binary. Get one at [XDA Developers](http://forum.xda-developers.com/showthread.php?t=2730422) for your CPU, then [upload to phone](http://stackoverflow.com/a/5022363/750510)
2. Run `adb shell`
3. Become superuser: `su`
4. Navigate to `/data/data/com.code44.finance/databases`
5. Open the database: `sqlite3 finance.db`
6. Insert what you need manually: `INSERT INTO exchange_rates (exchange_rates_currency_code_from, exchange_rates_currency_code_to, exchange_rates_rate) VALUES ('BYR', 'EUR', 0.00004170334);`

**Comment by mariebogarova** [comment]
Hi Madhead!

Were you actually able to solve this issue?

For some currencies the app still doesn't work properly and doesn't do the money conversion (for example: GBP, NZD,..). so if I wanna set my new "account" in those currencies, the money exchange rate is always 1, even it's not true (for example 1 NZD would show as 1 CHF). 

I don't see the option to set it manually.

Thanks for advises!

**Comment by madhead** [comment]
Workaround works only for rooted phones...

**Comment by mariebogarova** [comment]
Thanks,
It sais that root access is available but its not installed. Im gonna check what it is exactly, im not good in those stuff but it would be worhty to find out :)
