### ISSUE TITLE
Change income categories

### ISSUE THREAD

**Issue by enishemed** [mvarnagiris/financius#40]
The user could change the income categories

**Comment by baptistemarchand** [comment]
What do you mean?
If you go to the "settings/categories" page there is a dropdown menu to switch between "Expense" and "Income".

**Comment by enishemed** [comment]
You are right. Sorry for that.  I could not realize switching.
19 Kas 2013 23:43 tarihinde "Baptiste Marchand" notifications@github.com
yazdý:

**Comment by mvarnagiris** [comment]
Categories page will change and it will be more obvious that you can switch between expense and income
