### ISSUE TITLE
Deleting all transactions between two specified dates

### ISSUE THREAD

**Issue by enishemed** [mvarnagiris/financius#41]
Users could delete all transactions between specifed dates.

**Comment by mvarnagiris** [comment]
This sounds like a very specific edge case. Why would you want to do that?

**Comment by enishemed** [comment]
I understand that this is a very specific and unusual case. But it is important especially for future transactions. If I wonder my prospective future balance, and record the possible future transactions. It is difficult to delete transactions step by step.
I know the app has more important issues to upgrade, but this issue can be considered for future.

**Comment by mvarnagiris** [comment]
There must be a better solution to predict future balance rather than creating transactions. This prediction will be implemented at some point
