### ISSUE TITLE
Possibility to edit category names

### ISSUE THREAD

**Issue by veso16** [mvarnagiris/financius#42]
It is missing functionality for me. 
To be able to edit main categories and subcategories. 
What we will do if we mistaken the name and already save it.

**Comment by mvarnagiris** [comment]
You can edit.

**Comment by veso16** [comment]
Please, excuse my incompetence, but I didn't see where to tap for editing preinstalled categories of expenses. 
Version is 0.9.11 on Huawei Ascent G700.
Also I can not edit new categories, created by me.

**Comment by mvarnagiris** [comment]
When you click on a category, press the menu button. There will be an option to edit

**Comment by veso16** [comment]
Thanks! 
At the end I found nomenclature in settings, not from transaction screen, like I tried before.
