### ISSUE TITLE
Category search is broken

### ISSUE THREAD

**Issue by mvarnagiris** [mvarnagiris/financius#44]
For example, I have a category "Phone". 
If I search "p", it finds Phone. 
If I search "ph", it doesn't. 
If I search "hone", it finds Phone as well.
So it looks like there is some problem with the first letter. It doesn't depend if the letter is uppercase or lowercase.﻿

**Comment by walter-juan** [comment]
I check this and for my app it works fine (v0.9.11).
In the code the strings to search are "toLowerCase" for search.

**Comment by mvarnagiris** [comment]
Category search is going away in next release
