### ISSUE TITLE
Autofill relevant fields in the transaction editor

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#5]
In order to save the user some time and to make the editor a bit less intimidating, the editor should try to autofill as many fields as possible depending on what operation opened it. Here are some example mockups:

![financius editor 1](https://f.cloud.github.com/assets/694794/1509532/1ff85c96-4a52-11e3-9fe1-e68f0b4acee3.png)

This is the basic editor, that would open when you press "Create transaction" from the Overview. Since Financius doesn't know what kind of operation you want to create, all the fields are empty.

![financius editor 2](https://f.cloud.github.com/assets/694794/1509536/5137b392-4a52-11e3-92d1-314e93a4411b.png)

If you press "Repeat" from a transaction's details screen, however, the editor autofills all the fields based on their previous value for that transaction. That way the user only has to correct whatever has changed, and press "Done".

![financius editor 3](https://f.cloud.github.com/assets/694794/1509541/97587848-4a52-11e3-8ffa-e896cb3c593a.png)

If you press "Expense" or "Income" from an Account screen, the editor autofills the relevant field with that account. If you create an expense it's added to the "From" field, and if you add an income it's added to "To".

![financius editor 4](https://f.cloud.github.com/assets/694794/1509544/d01265f4-4a52-11e3-8ef7-8635d797a1c1.png)

If you're on the details screen of an expense category and press "Create expense", the expense's name is added automatically to the "To" field. If you're on the details screen of an income category and press "Create income", it's added to the "From" field.

![financius editor 5](https://f.cloud.github.com/assets/694794/1509548/18647e00-4a53-11e3-80c5-8d1ec4d4a952.png)

If you press "Lend" from a Contact screen, the contact's name is added to the "To" field. But if you press "Borrow", it's added to "From".

![financius editor 6](https://f.cloud.github.com/assets/694794/1509549/3d5f5d74-4a53-11e3-914c-aaa2b2894c7f.png)

If you press "Create expense" from a Group screen, the group's name is added to the  "Concept" field, and its category and the participants' names are added to the "To" field.

Even if you open an editor with empty fields, filling some fields should autofill others. For example, if you start filling the "Concept" field and you select a group's name, all its participants should be added to "To".

And if you select a previous transaction's name, all the remaining fields should be autofilled to match their values the last time you created that transaction.

**Comment by mvarnagiris** [comment]
The style of the app is not going to change at this moment. And there will be only one entry point to create new transaction for now. Let's keep it simple.

**Comment by frandavid100** [comment]
I take it "one entry point" means that there will only be "create transaction" buttons, and then you'll have to choose the transaction type once you're inside the editor?

**Comment by mvarnagiris** [comment]
Yes. Very simple :)
