### ISSUE TITLE
Advance payments

### ISSUE THREAD

**Issue by lilfo** [mvarnagiris/financius#50]
I often use not-confirmed transactions as reminders. It would be cool if i could set part of the transaction confirmed to remind the advance payments.

**Comment by mvarnagiris** [comment]
You can already do this. Just uncheck "confirmed" box when creating transaction

**Comment by lilfo** [comment]
i'll give you an example. I'm doing a work for a guy who have to pay me 200$. I set transaction. I do a fist part of the job and he gives me 100$.. how can remind this with the app?

**Comment by mvarnagiris** [comment]
Create a transaction that is not confirmed. As I said, you need to uncheck Confirmed checkbox

**Comment by lilfo** [comment]
So i have to create the first transaction (200$) and uncheck "confirmed" checkbox.. after a while i receive 100$ so i go to the transaction, change the import to 100$ (unchecked) and create a new transaction of 100$ (checked)?

**Comment by mvarnagiris** [comment]
That is correct :) I know it's not the most convenient way, but the thing you're asking is very specific
