### ISSUE TITLE
Attached keyboard : Winner suggestion : AVOID IRRETATING NUMERAL INPUT POP UP

### ISSUE THREAD

**Issue by susheel227** [mvarnagiris/financius#51]
---------------------------------------------|  
|   X discard             Done       |  
|   11 December        17:45      |  
|   MyAccount                         |  
|   [color]   category                 |  
|   12$ {currency input box }     |  
|                                            |  
|   Note                                  |  
|                                            |  
|   Confirmed                          |  
|   Includes in report                |  
|   expense income transfer     |  
|   -----------------------------------------
this is your add transaction screen.
as i am seeing many suggestion, please make all them optional inputto avoid simplicity of app.
also make a line of 1 2 3 4 5 6 7 8 9  0 below , so that we may avoid pop up of number input while adding transaction.
1: open input pop up after clicking input box
2: fill simple number in that input without clicking input box i f user click on number row as i suggested

**Comment by susheel227** [comment]
whose issue get considered here. i got no reply. i posted two posts

**Comment by mvarnagiris** [comment]
Everyone's issues are considered here. Currently I'm very busy with other things continue the development on Financius next year.

If you could explain this issue in more detail that would be helpful

**Comment by mvarnagiris** [comment]
I think I understand what you are suggesting. I don't think that would be a good idea.
