### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by susheel227** [mvarnagiris/financius#52]
If we have same category as our csv from other source can we import it

**Comment by cronco** [comment]
+1, csv import is a must for migrating from other apps.

**Comment by benghansen** [comment]
Is there a solution yet to this problem. I am trying to bring my records from another app and some older records but I don't feel like adding each one in manually.

**Comment by mvarnagiris** [comment]
There is not solution for this problem and I doubt that it's coming any time soon

**Comment by mvarnagiris** [comment]
Closing this, as this is too big of a task
