### ISSUE TITLE
How to load the project

### ISSUE THREAD

**Issue by lijunle** [mvarnagiris/financius#55]
Hi, Mvarnagiris.

Thank you for providing such a good software. I like it very much though there are lots task to do to complete the whole function.

I am trying to do some contributions for this project. But, I encounter big challenge because I do not know how to start!

After several attempts and web search, I realize I should use Android Studio instead of Eclipse. But then I am consufed which folder should be the root of project and why _build.gradle_ file is empty?

I think a guide or wiki or some links should be better to be provided for the starters. And, there are 4 branches, what is differences between them, there is not enough information.

By the end, thank you for your good expense record software. :+1:

**Comment by mvarnagiris** [comment]
Ah good point. I will write a description about how to contribute. But you should use gradle file that is one level inside :)
