### ISSUE TITLE
Addition of new 4.4 style DateTime picker ?

### ISSUE THREAD

**Issue by tdkl** [mvarnagiris/financius#56]
Possible addition of the new Google style DateTime pickers as seen in 4.4 Clock or Google Calendar apps.

As suggested here : https://plus.google.com/105164021049381796596/posts/6bsXob2ba6x

**Comment by mvarnagiris** [comment]
:+1: Will do :)

**Comment by tdkl** [comment]
@mvarnagiris Awesome, thank you :]

**Comment by mvarnagiris** [comment]
Done
