### ISSUE TITLE
Transaction currency different than account currency

### ISSUE THREAD

**Issue by sanchosk** [mvarnagiris/financius#58]
I'd like to have an ability to set transaction currency different than the actual account currency - for example, I have an account in CZK with income in CZK, I am paying for almost everything using the card for this account, but most of my payments are done in EUR currency.
Currently I have no option to select currency, just the accounts.

**Comment by mvarnagiris** [comment]
But when you pay there might be some extra fees for converting. Also what exchange rate to use? No one knows the exact exchange rate they use for these transactions

**Comment by eevleevs** [comment]
+1. Would be very useful to keep track of credit card balance if you travel abroad. There the conversion fee is fixed (1.75% on mine) and even if there could some difference it would be good to check your bill. Please consider this again.

**Comment by mvarnagiris** [comment]
I think this would be different for each bank, therefore making it very hard to implement. Plus technically when you pay, the money that leaves your account is in the currency of your account, not the destination account. Maybe modifying the calculator could be possible to make these types of transactions easier
