### ISSUE TITLE
Future Balance

### ISSUE THREAD

**Issue by subratpatel** [mvarnagiris/financius#62]
When I am entering confirmed transactions for Feb 14 in Jan 14 the overview screen shows balance for Feb 14 but has labeled it as Jan 14. It should display current months balance only.

And one more issue if account is defined as "Not Include in Total" then it should not appeared in Transaction Head in Overview Screen.

Thank you in advance for these suggessions and its really a fantastic app as usable one and with best looks.

**Comment by mvarnagiris** [comment]
All transactions are included if they are "confirmed". Doesn't matter if they are in the future or not. It's up to user to decide what is included and what is not included.

Could you give more description about your second issue (with screenshots) But create a separate issue for that. I'm closing this one
