### ISSUE TITLE
KitKat Styling

### ISSUE THREAD

**Issue by panz3r** [mvarnagiris/financius#63]
I think it would be good to have some KitKat styling in the app such as translucent Status and Navigation bar.

This can be useful http://mindofaandroiddev.wordpress.com/2013/12/28/making-the-status-bar-and-navigation-bar-transparent-with-a-listview-on-android-4-4-kitkat/

**Comment by mvarnagiris** [comment]
At the moment I don't really see how that can benefit the app. Adding this just for the sake of adding doesn't make sense
