### ISSUE TITLE
Add categories for transfers

### ISSUE THREAD

**Issue by leoetlino** [mvarnagiris/financius#64]
Would it be possible to add categories for transfers as well? Thank you!

**Comment by mvarnagiris** [comment]
In what situation would you like to have a category for a transfer?

**Comment by firnasz** [comment]
Yes, it will be useful such as transfer in bank accounts like "ATM Withdrawal", "Cash Deposit", etc.

**Comment by assoc** [comment]
Absolutely not useful. If you use deposit you have special account for it. Now transfers displayed with point-to-point captions ("cash"->"deposit"). Categories not needed.

**Comment by firnasz** [comment]
Yes, you are right. But for reporting purpose or grouping purpose we might need.

**Comment by leoetlino** [comment]
Simply because it might not be useful for you does not mean it is
"_absolutely_ not useful". As Firnas Aliyar has said, this might be
used for reportings, but maybe this could be done with a message we
could add to the transfer transaction?

2014-03-28 11:50 UTC+01:00, Firnas Aliyar notifications@github.com:

> Yes, you are right. But for reporting purpose or grouping purpose we might
> need.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mvarnagiris/Financius/issues/64#issuecomment-38907284

## 

Cordialement, Léo

**Comment by assoc** [comment]
First, we need working filter. In general, it is the main problem.
And yes, I wrote my opinion.

**Comment by mvarnagiris** [comment]
Tags should solve this problem. #54

**Comment by patcon** [comment]
Example of use-case that I just ran into today:

Paying a bill, and if I put it on card and everyone else gives me cash, then I want the bill amount in the transaction itself (so that I can cross-check with my statements on that account), but I want the transfer (from CC to cash account) to have a category so that it will subtract the amount from the charts. Otherwise, it will show me as having a $100 food category expense, when in reality it was just $20 food expense and a $80 transfer to cash that shouldn't be in charts

**Comment by patcon** [comment]
Can we re-open this? It seems a valid use-case, as otherwise I need to create 3 transactions that need to be all connected

**Comment by patcon** [comment]
If you'd rather not discuss this on a closed issue, please let me know and I'll try to write a more clear use-case in a new ticket. That use-case essentially involves painlessly splitting bills with friends and colleagues, which is very common (at least in my experiences in bigger cities). Thanks!

**Comment by mvarnagiris** [comment]
What you described there is a split transaction rather than categories on transfers. Categories on transfers would not solve this problem

**Comment by patcon** [comment]
You're right. I realized last night that I misremembered how another app worked.

I think the thing that threw me off was that negative value expenses (ie. refunds) don't act as expected in reports. But I'll investigate more and file another issue if needed :)
