### ISSUE TITLE
Credit type accounts

### ISSUE THREAD

**Issue by baxtian** [mvarnagiris/financius#65]
A credit type account would require an extra value named "credit limit" in addition to the balance, and the difference between those values would go as a negative number into the overview.

Also, pay a credit card bill would require to split a transaction: part of it is a transference, and part of it is an expense.

**Comment by mvarnagiris** [comment]
I think this should be possible to achieve already. This is very specific feature and I don't think it's necessary for the majority of the users.

**Comment by mvarnagiris** [comment]
I think this is out of scope for this app
