### ISSUE TITLE
Option to include/exclude future transactions into/from accounts balance

### ISSUE THREAD

**Issue by enishemed** [mvarnagiris/financius#67]
There should be an option to include/exclude the future transactions into/from accounts balance. A checkbox can be added to accounts menu. The caption of the checkbox is "Add future transactions into balance". If the checkbox is checked then the future transactions will be added to accounts balance and if unchecked then the future transactions will be excluded from accounts balance.

**Comment by mvarnagiris** [comment]
It is already possible. You have "Confirmed" checkbox in transaction

**Comment by enishemed** [comment]
Yes i know there is "confirmed" checkbox in transaction. But i think it will be good to have an option that allows us to include/exclude the future transactions in today balance. Otherwise in current situation, lets say I have more than 100 future transactions, I have to unchecked "Confirmed" checkbox to see the today balance.

**Comment by mvarnagiris** [comment]
Yup. I've only heard this request from you. So this is just too niche for me to consider implementing it
