### ISSUE TITLE
Use From / To fields in the editor

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#7]
The current transaction editor changes depending on what type of transaction you want to create (income, expense or transfer). If the app ever supports lendings, borrowings and group expenses, it would be very hard (and confusing to the user) to also use different editors for each of them.

Therefore, I think it would be very helpful to use a single editor for every type of transaction. That can be done by using From / To fields:

![financius editor 1](https://f.cloud.github.com/assets/694794/1509667/eb6e2d82-4a58-11e3-9228-c0859abee96f.png)

It's actually very simple; From specifies where the money comes from, and To specifies where it goes.

From = income category, To = account → the transaction is an income.
From = account, To = expense category → the transaction is an expense.
From = account, To = account → the transaction is a transfer.
From = contact, To = account → the transaction is a borrowing.
From = account, To = contact → the transaction is a lending.

Group expenses are admittedly more complex, but can also be attained:

From = account + contact + another contact → it means that you and other two people paid equally for the expense.
To = category + contact + another contact → it means that you and two other people enjoyed the expense equally.

**Comment by mvarnagiris** [comment]
I think this might bring a lot of confusion. But it would be nice to have some other way to change transaction type.

**Comment by frandavid100** [comment]
So having a different editor for each transaction type is the way to go, then?

I think that's fine, but I don't really like those buttons to change type, right there in the editor. Maybe instead of "Create transaction", each screen could have buttons for each relevant transaction type?

For example, if you're on an account screen you have "Create expense" and "Create income". If you're on a contact screen you have "give money" and "take money", and so on. And once you enter the editor you can't change the transaction type.

Would that be better?

**Comment by mvarnagiris** [comment]
I would like to consider changing the way user changes transaction type, because transfer and income are very rare, so there is no point in occupying that space always at the bottom

**Comment by frandavid100** [comment]
I'll try to find an alternative way that you like more, but I really don't think the user should have to change the transaction type once he's inside the editor. I think he should only have to fill the relevant fields, hit Done and be done with it.
