### ISSUE TITLE
Income report

### ISSUE THREAD

**Issue by RevigBreizh** [mvarnagiris/financius#70]
A big thank for your application. It is an amazing job. I love the design and the facility of use.
Would it be possible to add reports for the incomes? The same page as the page for the expenses would be great!

**Comment by ghost** [comment]
Agreed. Would be lovely.

Perhaps there could be tabs similar to the "Expense, Income, and Transfer tabs" when inputting a transaction.

**Comment by firnasz** [comment]
Yes, I too want this feature.

**Comment by Nyaaa** [comment]
This feature is absolutely necessary!

**Comment by mvarnagiris** [comment]
#280
