### ISSUE TITLE
Period design

### ISSUE THREAD

**Issue by Carpera** [mvarnagiris/financius#76]
The period panel is not working on my Moto G but I saw that the bug is already reported. Anyway, even if I don't know exactly how it should work, I would like to submit an idea. Indeed, instead to propose directly to the user to customise its period, some pre-defined choices can be presented. Therefore, the user can easily see its expenses/incomes for one:
_ day
_ week
_ month
_ year
_ custom period

However, in order to avoid translation to other languages. I would like to propose the designs attached (sorry, they are made from power point). I don't know if they are relevant but they represents the basic idea I have in mind.

Again, I don't know how periods should work exactly but I guess they are filters for the presentation of expense/income. So, I imagine that once one of the 4 first items selected, for instance the week and if the user swipes the screen to the left or to the right, the expense/income presented should switch to the previous or next week.

Hopping this is a good idea and it is well expressed even if my English is not very well.

![preiod_design_2](https://f.cloud.github.com/assets/6629928/2119552/8095a7b6-9174-11e3-8fa7-ac13f6bcdc6d.png)
![preiod_design_1](https://f.cloud.github.com/assets/6629928/2119553/80b52faa-9174-11e3-8f3b-e378afd8eec4.png)

**Comment by Carpera** [comment]
Ah, I forgot! the collored icons represent the selected item.

**Comment by mvarnagiris** [comment]
Very nice suggestion!

**Comment by mvarnagiris** [comment]
I think this is not relevant any more. Simple dialog is good enough for now

**Comment by Carpera** [comment]
I agree with that. The app changed quite a lot.

Thanks,
Le 3 janv. 2015 14:02, "Mantas Varnagiris" notifications@github.com a
écrit :
