### ISSUE TITLE
Repartition depth

### ISSUE THREAD

**Issue by Carpera** [mvarnagiris/financius#77]
Suggestion:

It would be nice to see the categories report a bit more interactive. The idea I have consist to allow going deeper in the expense/income repartition. Indeed, each major category can have several sub-cateories. 

Therefore, by typing on one major category (on the circle graph or one category in the list), the screen should show the repartition of each sub-categories of the selected major category. Attached, I propose one design in order to illustrate what I have in mind.

The sub-categories may kept the color of the selected major category but may add a gradient for a better view.

Hopping this idea is relevent and clear enough.

![repartition_1](https://f.cloud.github.com/assets/6629928/2119620/bc3c7efc-9179-11e3-893e-3f9514f05745.png)

**Comment by assoc** [comment]
or another variant (same concept):
http://i.imgur.com/XmPbpBM.png

**Comment by Carpera** [comment]
Why not! I saw in expense manager (https://play.google.com/store/apps/details?id=at.markushi.expensemanager) that the elemants of the circle graph can be pressed. So it is feasible.

**Comment by assoc** [comment]
It was my previous expense manager :P. Database port was not easy, but it is possible.
Good features can be used here, why not?

**Comment by mvarnagiris** [comment]
I was thinking of doing something similar to go deeper. The problem is that I don't really like limiting Color selection to fixed colors only and it would be hard to show shaded colors from a random color. But I guess something can be done to solve this.

**Comment by mvarnagiris** [comment]
Subcategories are going away in next release
