### ISSUE TITLE
improve "Create transaction" part

### ISSUE THREAD

**Issue by xmas2** [mvarnagiris/financius#78]
hi

it would be great if when one presses "create transaction" it would automatically open part with inserting needed sum (there on top could be buttons with Expense/income to choose), and after it is entered - would open categories.

it will be great as almost all transactions are filled on the run - so less pressing will be faster and more convinient

**Comment by assoc** [comment]
Already in issue 72/74

**Comment by xmas2** [comment]
sorry, missed those

**Comment by mvarnagiris** [comment]
:+1:

**Comment by mvarnagiris** [comment]
Only doing this for amount.
