### ISSUE TITLE
Transactions order issue, dashclock suggetion

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#79]
- [ ] Sorting problems. (http://i.imgur.com/bKp0zaF.png)
  For example, I created 4 transactions without changing dates (left at image), now there are 4 elements with id's 1-4 and 2 timestamps. Then I changed time to 0:00 GMT at all ofthem and element order was broken. Maybe one timestamp fields can be dropped from table?
- [ ] Currency decimals at dialogs & widget
  I set 0 decimals for main currency, but in add transaction dialog and dashclock widget shown 2 decimals (.00),
- [ ] Allow to change dashclock widget sum to any account balance.

**Comment by mvarnagiris** [comment]
@assoc Could you split these in separate issues. And if you could it would be better to upload images straight to description rather than URL.
