### ISSUE TITLE
Accounts screen suggestion (upd)

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#80]
I suggest full redesign of accounts screen. Replace list and screen with additional data by cards with all information and actions. Of cource, unnesessary screen must be removed (with account details like averages,sum,include in totals and etc.).
This is it:
![card](https://f.cloud.github.com/assets/6578444/2152397/b1c7ddbc-9418-11e3-95fb-035cca5ddf8f.png)
From left upper to right bottom corner:
Account name, if very long - use white shadow with '...' to cut it.
Options button contains menu with Edit and Delete items.
Current sum at account.
All Income, all expence; coloured. Can be replaced by averages (but it is not good).
Last usage (count of usages can be added in brackets).
Icon "include in totals", icon "show in selection"; if not checked in options - icon are hidden.
Cards are very perspective solution.
UPD:
![a](https://f.cloud.github.com/assets/6578444/2168448/fe957614-953e-11e3-8b80-2479eff9537c.png)

**Comment by leoetlino** [comment]
Well - it simply does not fit into any Android app. This would instead
be the typical layout for a Modern UI app.

2014-02-12 20:18 UTC+01:00, assoc notifications@github.com:

> I suggest full redesign of accounts screen. Replace list and screen with
> additional data by cards with all information and actions. Of cource,
> unnesessary screen must be removed (with account details like
> averages,sum,include in totals and etc.).
> This is it:
> ![card](https://f.cloud.github.com/assets/6578444/2152397/b1c7ddbc-9418-11e3-95fb-035cca5ddf8f.png)
> From left upper to right bottom corner:
> Account name, if very long - use white shadow with '...' to cut it.
> Options button contains menu with Edit and Delete items.
> Current sum at account.
> All Income, all expence; coloured. Can be replaced by averages (but it is
> not good).
> Last usage (count of usages can be added in brackets).
> Icon "include in totals", icon "show in selection"; if not checked in
> options - icon are hidden.
> Cards are very perspective solution.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mvarnagiris/Financius/issues/80

## 

Cordialement, Léo

**Comment by assoc** [comment]
But what about Google Now? Cards enable you to visualize more data, and it's better than plain lists.

**Comment by leoetlino** [comment]
I'm not talking about this - cards are part of the Android UI - but
your layout is not.

2014-02-12 21:00 UTC+01:00, assoc notifications@github.com:

> But what about Google Now? Cards enable you to visualize more data, and it's
> better than plain lists.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mvarnagiris/Financius/issues/80#issuecomment-34910526

## 

Cordialement, Léo

**Comment by assoc** [comment]
It's just concept. Someone can make better variant.

**Comment by mvarnagiris** [comment]
I agree that current "Account detail" page is not very good. But this idea is too vague and not complete.

**Comment by assoc** [comment]
But what about this?
![a](https://f.cloud.github.com/assets/6578444/2168448/fe957614-953e-11e3-8b80-2479eff9537c.png)
It's more clear. "Hidden" label with icon must me hidden if account isn't hidden (card size will be same). Dots at right corner calls edit menu.

**Comment by mvarnagiris** [comment]
Where does this card go?

**Comment by assoc** [comment]
To accounts screen.
Account picker (from dialogs) can be provided via cards.

**Comment by mvarnagiris** [comment]
Design is changing with next release
