### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#83]
![bkp0zaf](https://f.cloud.github.com/assets/6578444/2160877/3002bb42-94bf-11e3-91a4-2619b3b08740.png)

I wiped data and add 4 new transactions without changing dates (left image), now there are 4 elements with id's 1-4 and 2 different timestamps (why?).
Then I changed time to 0:00 GMT at all ofthem and element order was broken.
2 ways: change 4 last digits of timestamp to 0 if record was edited or remove milliseconds from timestamp.
Maybe one timestamp field can be dropped from table?

**Comment by mvarnagiris** [comment]
As a user you should not care how many timestamps I'm using. But anyway, one timestamp is not used anymore

**Comment by assoc** [comment]
But sorting is broken! I talk about it.

**Comment by mvarnagiris** [comment]
Sorting is working as expected. When you set exactly the same time to your transactions, they can be in any order

**Comment by assoc** [comment]
Using both timestamp and then id can be better. Now all difference in timestamp milliseconds, which is not true in fact.

**Comment by mvarnagiris** [comment]
There is no guarantee that the ID will be in correct order
