### ISSUE TITLE
Same editor for categories and subcategories

### ISSUE THREAD

**Issue by frandavid100** [mvarnagiris/financius#9]
I think that using Financius would be simpler to use if both categories and subcategories had the same editor:

![financius category editor](https://f.cloud.github.com/assets/694794/1509759/9b3afd6e-4a61-11e3-98f8-d17425922db1.png)

If you fill the category name but leave the subcategory name empty, you're creating a category. If you edit the subcategory and change the category name, you're changing what category that subcategory belongs to (ideally, the "Category name" field should let you autocomplete from existing categories).

That aside, it could be useful to give categories some of the traits of accounts, e.g. letting you choose whether or not you want them to show in the totals and in the autocomplete, and letting you add a note to them.

**Comment by mvarnagiris** [comment]
I think this would bring a lot of confusion. Users would know what to expect when they are creating categories. I wouldn't know how to create Main category, because it's asking for subcategory name. What if I want to add to current main category?

**Comment by frandavid100** [comment]
So, one editor for categories and another for subcategories, then?

**Comment by mvarnagiris** [comment]
Well technically it's the same editor with some fields hidden

**Comment by frandavid100** [comment]
Yep, that's what I meant. Different editor interfaces, but still the same editor.
