### ISSUE TITLE
Better required fields indication

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#90]
Now if you are entered invalid data (missing sum, empty name, etc) small animation are used. If animations are disabled in Android, there are no way to find required fields.
I suggest too use something like in Timetable app (red circles with ! at right part of input area) or quest change color of element bottom border (red).

**Comment by mvarnagiris** [comment]
This sounds like a very rare "what if" case, but I'll leave it for now as a suggestion

**Comment by mvarnagiris** [comment]
#278
