### ISSUE TITLE
Crash at category search in new version

### ISSUE THREAD

**Issue by enishemed** [mvarnagiris/financius#91]

**Comment by mvarnagiris** [comment]
Duplicate #88 
Please read FAQ section here https://github.com/mvarnagiris/Financius

**Comment by mvarnagiris** [comment]
Could you provide more info?

**Comment by mvarnagiris** [comment]
I updated FAQ section again. https://github.com/mvarnagiris/Financius/blob/dev/README.md

**Comment by enishemed** [comment]
When entering a New transaction, I try to search category to choose and when clicked on category fiels it stopped and crashed and goes to the main menu.

**Comment by enishemed** [comment]
When entering a New transaction, I try to search category to choose and when clicked on category field it stopped and crashed and goes to the main menu.

**Comment by mvarnagiris** [comment]
Cannot reproduce. Did you send crash report?

**Comment by mvarnagiris** [comment]
I think I found the issue. There were similar issues reported via crash reports. Fixed
