### ISSUE TITLE
Drag&drop categories not working

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#92]
Settings>Categories
Long press starts moving, but position doesn't changes.
v0.9.13 @ android 4.4

PS: short bugfixes description at log can help us to test app.

**Comment by enishemed** [comment]
I tested it and yes moving of category doesn't work.

**Comment by mvarnagiris** [comment]
Yup I've noticed that myself. I'll fix this with next release

**Comment by mvarnagiris** [comment]
Reordering actually worked, but it just didn't update in the list. But I fixed it anyway :)
