### ISSUE TITLE
Time as optional information

### ISSUE THREAD

**Issue by assoc** [mvarnagiris/financius#93]
Add to settings checkbox to toggle "use time".
If not checked use timestamp of 0:00 gmt and hide time from "add transaction" dialog (field and time picker). It can add +1 to speed and resolve sorting problem. Will it be checked by default --  I don't know.

**Comment by mvarnagiris** [comment]
I might be better to just split that button into two again

**Comment by mvarnagiris** [comment]
Time and date are now split
