### ISSUE TITLE
Reports percentage not always is 100%

### ISSUE THREAD

**Issue by jcchak** [mvarnagiris/financius#94]
Dear Mantas,

I found that in "Reports" the sum of all the categories is not always 100%. Sometimes is above and sometimes is under 100%. Can you take a look to this, please? :)

P.S: by the way, congrats for you app! for me it's the best one under its category!

![2014-02-09 08 09 06](https://f.cloud.github.com/assets/6629633/2177372/0abef5fa-9611-11e3-9873-d2d84e5991f5.png)
![2014-02-15 07 08 13](https://f.cloud.github.com/assets/6629633/2177373/0cad5956-9611-11e3-9fef-9c689d3046e2.png)

**Comment by mvarnagiris** [comment]
It happens because that percentage is rounded.
So your first example could be:
48 - 48.2
44 - 44.4
7.4 - 7.4

**Comment by jcchak** [comment]
Yes, I supposed that was about rounding :) But I wanted to say that it's strange to obtain a 99% or a 101%, as it should be always a 100%, as that report is counting all the transactions.

So in the first example I think it should be rounded something like 48, 44, 8, and in the second it should be something like (for example) 56, 40 and 4.

**Comment by mvarnagiris** [comment]
Then the data would be more not correct :) because 7.4 = 7 not 8

**Comment by jcchak** [comment]
I agree that rounding 7.4 to 7 it's not correct, but if all the percentatges sums 99% or 101% it seems there is something wrong.

What if decimals where displayed there? If it's not checked that all the percentatges sums 100%, at least with the decimals would be a little bit more precise :)

**Comment by mvarnagiris** [comment]
Decimals take up space. I'm going to redo that report screen anyway so it might look different and maybe with decimals. My question is does it really matter for you if you've spent 45.3 or 45.4 percent on food?

**Comment by jcchak** [comment]
In fact with other budget apps I didn't pay that much attention to the statistics...but in your app, in that screen the percentages are quite "attractive" and can take someone's attention, so that's why I stopped one minute on them and noticed that something was happening with the sum.

Not really important at all, it's just a small detail. Maybe it because I have seen in other places that percentages are not well added and had the impression that they didn't care if the partial percentages made sense or not.

**Comment by mvarnagiris** [comment]
Well I'm gonna think about this when I will be redoing that report page

**Comment by ghost** [comment]
I think it's fine how it is. Maybe you could make it so long pressing on the number will reveal the decimal. Or put an option in the settings to either display whole numbers or decimal.

Number before long press: 44

Number after long press: 44.3

Either way, not a big issue. I wouldn't worry about this at all right now.

Thanks for the amazing app
