### ISSUE TITLE
Long press to delete one transaction

### ISSUE THREAD

**Issue by jcchak** [mvarnagiris/financius#95]
Hi Mantas,

Somehow I feel that there "many" steps when I want to delete one transaction. It would be possible to add the long press listener in transactions list to remove the selected "long pressed" transaction?

Thanks in advance.

**Comment by assoc** [comment]
Long press is associated with "select" action. It's already suggested at #75 (group actions).

**Comment by mvarnagiris** [comment]
Duplicate #75
