### ISSUE TITLE
Can't create a subcategory under the last main category

### ISSUE THREAD

**Issue by baptistemarchand** [mvarnagiris/financius#98]
Hi,

How to reproduce the bug:
- Go to Settings -> Categories
- Click the "+" to add a new category
- On the "pick main category" screen, try to select the last category on the list
- Nothing happens. If you try to select any other main category it works as expected.

Nexus 4
Android 4.4.2
Financius 0.9.13

Thank you

**Comment by mvarnagiris** [comment]
You're right. That is weird. I will fix it with next release

**Comment by mvarnagiris** [comment]
Subcategories are going away in next release
